# Generated by Django 4.2.3 on 2023-09-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='payment_id'),
        ),
    ]
